name: Gradle Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use Java 17
          distribution: 'adopt'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew  # Add executable permission to gradlew

      - name: Build with Gradle
        run: ./gradlew build  # Run the Gradle build command

      - name: List JAR files
        run: ls -l build/libs/  # List the contents of the build/libs directory
