name: Gradle Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use Java 17
          distribution: 'adopt'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew  # Add executable permission to gradlew

      - name: Build with Gradle
        run: ./gradlew build  # Run the Gradle build command

      - name: List JAR files
        run: ls -l build/libs/  # List the contents of the build/libs directory

      - name: Upload JAR to Artifactory
        run: |
          echo "Uploading JAR to Artifactory..."
          ARTIFACTORY_API_KEY="AKCpBtN8RniWvi19bumiTtGzhcWbRmBroNb1qXvxRqi9eP57NqFRxRNym4PKJKc3v7qssDSnT"  # Your Artifactory API key
          ARTIFACTORY_URL="https://testjavacigradle.jfrog.io/artifactory/gradle-task-gradle-dev-local"  # Your Artifactory URL

          # Upload the specified JAR file
          curl -H "X-JFrog-Art-Api:$ARTIFACTORY_API_KEY" \
            -T build/libs/sonar-scanner-gradle-basic-1.0.jar \
            "$ARTIFACTORY_URL/sonar-scanner-gradle-basic-1.0.jar"  # Uploading the JAR to Artifactory
